title:               Hunter Whaples
url:                 https://hwhaples.github.io
baseurl:             ""

markdown:            kramdown
highlighter:         rouge

exclude:             ['*.sublime-*', 'README.md', 'LICENSE', 'Gemfile', 'Gemfile.lock', 'vendor/bundle']

permalink:           pretty
paginate:            5
paginate_path:       /blog/:num

blog:
  truncated_preview: false

sass:
  sass_dir:          _sass
  style:             :compressed

author:
  name:              Hunter Whaples
  url:               hwhaples.com
  email:             hwhaples@hmc.edu

collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/

plugins:
  - jekyll-coffeescript
  - jekyll-paginate
  - jekyll-gist